In [1]:
import numpy as np

In [5]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [6]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

To create a single zero, you can use the `zeros` function:

In [8]:
np.zeros(1)

array([0.])

or the `arange` function:

In [9]:
np.arange(1)

array([0])