In [1]:
import numpy as np

numpy_array = np.array([3.14, 2.71, 1.18])

## Multiplication

In [2]:
numpy_array * 10

array([31.4, 27.1, 11.8])

In [3]:
numpy_array * -4.3

array([-13.502, -11.653,  -5.074])

In [4]:
numpy_array * 0

array([0., 0., 0.])

## Subtraction

In [5]:
numpy_array - 3.04

array([ 0.1 , -0.33, -1.86])

## Comparison

In [6]:
numpy_array > 2.5

array([ True,  True, False])