In [1]:
import numpy as np

In [2]:
a = np.array([6.0, 2.1, 8.2, 10.3, 5.4, 1.5, 7.6, 3.7, 9.8])

In [3]:
a[[0, 2, 4, 6, 8]]

array([6. , 8.2, 5.4, 7.6, 9.8])

In [4]:
a[[0, 1, 2, 3]]

array([ 6. ,  2.1,  8.2, 10.3])

In [5]:
a[[8, 5, 7, 4]]

array([9.8, 1.5, 3.7, 5.4])