In [2]:
import numpy as np

In [3]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
print(grid)

[[1 2 3]
 [4 5 6]]


In [4]:
grid[1, 0]

4

In [5]:
grid[:, 2]

array([3, 6])

In [6]:
grid[1, 1:]

array([5, 6])